#datasource config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/edumanager?useUnicode\=true&characterEncoding\=UTF-8&zeroDateTimeBehavior\=convertToNull&useSSL\=false
  username: root
  password: 19910511

#mybatis config
mybatis:
  typeAliasesPackage: com.lyd
  mapperLocations: classpath:*.xml

server:
  port: 8762
